GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
  "name": "Gabor Babor",
  "number": "040-123-456",
  "id": 420
}

###
DELETE http://localhost:3001/api/persons/194

###
PUT http://localhost:3001/api/persons/62c811834597373063b7f5e2 HTTP/1.1
content-type: application/json

{
  "name": "K",
  "number": "2"
}